name: vyra_trader
description: VyRaTrader Flutter frontend - polished
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^10.0.0-beta.4
  charts_flutter: ^0.12.0
  intl: ^0.17.0 # For DateFormat timestamps
  lucide_icons_flutter: ^3.1.5
  flutter_blurhash: ^0.9.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_dotenv: ^6.0.0
  lottie: ^3.3.2
  flutter_svg: ^2.0.9
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  page_transition: ^2.1.0
  animations: ^2.0.11
  pointycastle: ^3.6.2
  flutter_glow: ^0.3.0
  connectivity_plus: 7.0.0
  fluttertoast: ^9.0.0
  encrypt: ^5.0.3
  local_auth: ^2.1.8
  flutter_local_notifications: ^19.5.0
  animated_bottom_navigation_bar: ^1.3.0
  fl_chart: ^1.1.1
  web_socket_channel: ^3.0.1
  rive: ^0.13.3
  google_nav_bar: ^5.0.7
  flutter_inappwebview: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  animated_text_kit: ^4.2.2
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  just_audio: ^0.10.5
  audioplayers: ^6.1.0
  crypto: ^3.0.3 # for pin hashing
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  google_mobile_ads: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
